FROM nvidia/cuda:11.8.0-cudnn8-devel-ubuntu22.04

# Arguments defined in docker-compose.dev.yml
ARG user
ARG uid

ENV DEBIAN_FRONTEND noninteractive

RUN apt update && apt install -y \
    wget \
    git \
    python3 \
    libpython3-dev \
    libgl1-mesa-glx \
    python3-pip \
    python3-setuptools \
    libglib2.0-0

RUN apt-get install -y libsm6 libxext6

RUN pip3 install --upgrade pip

COPY requirements_dev.txt /home/
COPY requirements.txt /home/

RUN pip3 install --no-cache-dir -r /home/requirements_dev.txt

WORKDIR /app

ENV PYTHONPATH="/app:${PYTHONPATH}"

# Create system user run commands as user
RUN useradd -G www-data,root -u $uid -d /home/$user $user
RUN mkdir -p /home/$user/.composer && \
    chown -R $user:$user /home/$user

USER $user
